// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NordiskLuksusMVC.Models;

namespace NordiskLuksusMVC.Migrations
{
    [DbContext(typeof(NordiskLuksusContext))]
    [Migration("20190506151209_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NordiskLuksusMVC.Models.CustomerOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorName");

                    b.Property<string>("CustomerOrderText");

                    b.Property<int?>("ProductID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("CustomerOrder");
                });

            modelBuilder.Entity("NordiskLuksusMVC.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductName");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("NordiskLuksusMVC.Models.CustomerOrder", b =>
                {
                    b.HasOne("NordiskLuksusMVC.Models.Product", "Product")
                        .WithMany("CustomerOrder")
                        .HasForeignKey("ProductID");
                });
#pragma warning restore 612, 618
        }
    }
}
